### ISSUE TITLE
iPhone X Adaptation

### ISSUE THREAD

**Issue by helloDolin** [exponentjs/react-native-tab-navigator#159]
iPhone X，The tabBar height is 49 + 34

our code : tabBarHeight: 49

will update this?

**Comment by habovh** [comment]
Just made PR #166 to do just that. Even better, it does not include any hardcoded value and uses iOS 11 Safe Area concept.

In case you need to use it before the PR gets merged, here's the fork: [habovh/react-native-tab-navigator](https://github.com/habovh/react-native-tab-navigator).

**Comment by Mad-hu** [comment]
#165  
![qq 20171121094134](https://user-images.githubusercontent.com/13977755/33050648-f06f5970-cea0-11e7-8a91-aab51e199a14.jpg)
![qq 20171121094139](https://user-images.githubusercontent.com/13977755/33050651-f4924a30-cea0-11e7-8609-98b8cd186f31.jpg)

**Comment by habovh** [comment]
@Mad-hu I consider this implementation bad practice, since this won't work with other aspect ratio/screen dimensions that Apple may come out with in the future. For example you can adjust the window size on iPad using the split screen, and you might want to have access to the actual *safe area* concept that Apple provided along with iOS 11. This is way more flexible and scalable.

**Comment by jsfu** [comment]
use `tabBarStyle={{paddingBottom:xx,  height:xx}}`

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
