### ISSUE TITLE
android badgeText issue

### ISSUE THREAD

**Issue by melihmucuk** [exponentjs/react-native-tab-navigator#7]
badgeText doesn't work as expected.

![screen shot 2015-10-09 at 14 16 23](https://cloud.githubusercontent.com/assets/3147488/10392525/7cc2c808-6e90-11e5-8be8-d858276039be.png)

**Comment by timzaak** [comment]
+1.

**Comment by ide** [comment]
I'm not sure what to do about the border radius issue since I'm not sure how clipping and border radius work on Android. I'm using TabNavigator in an Android app so I will look into this in a few weeks but if you need this feature before then, I could use some help investigating potential solutions.

**Comment by amibition521** [comment]
need the answer

**Comment by songyouwei** [comment]
+1

**Comment by songyouwei** [comment]
I found out a solution,  your renderBadge should be like this:

```
      renderBadge={() =>
        this.state.badgeNum === 0? null:
        <View style={{alignItems:'center',backgroundColor:'red', width:16, borderRadius: 100, borderColor: '#d6d7da'}}>
          <Text style={{color: '#fff',fontSize:12}}>{this.state.badgeNum}</Text>
        </View>
      }
```

**Comment by bradbyte** [comment]
Thanks @songyouwei! My issue was the blue square for Android but circle on iOS. Now it's all the same.

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
